# Imports

In [1]:
import os
import glob
import spacy
import itertools
import numpy as np
import pandas as pd
from umap import UMAP
from hdbscan import HDBSCAN
from bertopic import BERTopic

from sentence_transformers import SentenceTransformer
from bertopic.representation import PartOfSpeech, MaximalMarginalRelevance
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.vectorizers import ClassTfidfTransformer

from gensim.corpora import Dictionary
from gensim.models.coherencemodel import CoherenceModel
from gensim.utils import simple_preprocess

random_seed = 42
min_samples = 5
min_cluster_size = 15
data_path = '../../data/positives_260226.json'
output_dir = 'output/bertopic_260226'

/home/cs/grad/mazumdmm/Masud/YouTube Project/YouTube-4SE/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
os.makedirs(output_dir, exist_ok=True)
try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    print("Downloading spaCy model 'en_core_web_sm'...")
    from spacy.cli import download
    download("en_core_web_sm")

In [3]:
# Read all json files in the directory
df = pd.read_json(data_path)
print(f'Total videos: {len(df)}')

Total videos: 62760

In [4]:
# prepare documents for topic modeling (title + description)
ids = df['id']
documents = (df['title'] + "\n" + df['description'])
documents = [" ".join(doc.split()) for doc in documents]
print(f'Total documents: {len(documents)}')

Total documents: 62760

In [5]:
# Save documents to a text file
with open(os.path.join(output_dir, 'documents_260226.txt'), 'w', encoding='utf-8') as f:
    for doc in documents:
        f.write(doc + '\n')

In [9]:
embedding_model = SentenceTransformer("all-mpnet-base-v2")
embeddings = embedding_model.encode(documents, normalize_embeddings=True, batch_size=2, show_progress_bar=True)
np.save(f'{output_dir}/embeddings_260226.npy', embeddings)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 415.21it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100%|██████████| 31380/31380 [10:43<00:00, 48.79it/s]

In [ ]:
# Apply BERTopic
topic_model = BERTopic(verbose=True)
topics, probs = topic_model.fit_transform(documents)

In [ ]:
# Display topics
topic_info = topic_model.get_topic_info()
topic_info

# V2

In [ ]:
embedding_model = SentenceTransformer("all-mpnet-base-v2")
embeddings = embedding_model.encode(documents, normalize_embeddings=True, batch_size=2, show_progress_bar=True)
np.save(f'{output_dir}/embeddings.npy', embeddings)

In [ ]:
umap_model = UMAP(n_neighbors=15, n_components=5, metric='cosine')
hdbscan_model = HDBSCAN(min_cluster_size=350, prediction_data=True)
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)
vectorizer_model = CountVectorizer(stop_words= "english", ngram_range=(1, 3), min_df=0.1)
representation_model = [PartOfSpeech("en_core_web_sm"), MaximalMarginalRelevance(top_n_words=20, diversity=0.3)]

In [ ]:
umap_model = UMAP(n_neighbors=15, n_components=5, metric='cosine')
hdbscan_model = HDBSCAN(min_cluster_size=350, prediction_data=True)
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)
vectorizer_model = CountVectorizer(stop_words= "english", ngram_range=(1, 2), min_df=10)
representation_model = [PartOfSpeech("en_core_web_sm"), MaximalMarginalRelevance(diversity=0.3)]

topic_model = BERTopic(
    # embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
    representation_model=representation_model,
    calculate_probabilities=True,
    top_n_words=10,
    verbose=True,
)

In [36]:
topics, probs = topic_model.fit_transform(documents, embeddings=embeddings)
topic_model.get_topic_info()

2026-03-10 15:56:01,197 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.01, n_components=5, n_jobs=1, random_state=42, verbose=True)
Tue Mar 10 15:56:01 2026 Construct fuzzy simplicial set
Tue Mar 10 15:56:01 2026 Finding Nearest Neighbors
Tue Mar 10 15:56:01 2026 Building RP forest with 16 trees
Tue Mar 10 15:56:02 2026 NN descent for 16 iterations
	 1  /  16
	 2  /  16
	 3  /  16
	 4  /  16
	Stopping threshold met -- exiting after 4 iterations
Tue Mar 10 15:56:07 2026 Finished Nearest Neighbor Search
Tue Mar 10 15:56:07 2026 Construct embedding

Epochs completed:   3%| ▎          6/200 [00:00]

	completed  0  /  200 epochs

Epochs completed:  12%| █▏         23/200 [00:02]

	completed  20  /  200 epochs

Epochs completed:  22%| ██▏        43/200 [00:05]

	completed  40  /  200 epochs

Epochs completed:  32%| ███▏       63/200 [00:07]

	completed  60  /  200 epochs

Epochs completed:  42%| ████▏      83/200 [00:10]

	completed  80  /  200 epochs

Epochs completed:  52%| █████▏     103/200 [00:13]

	completed  100  /  200 epochs

Epochs completed:  62%| ██████▏    123/200 [00:15]

	completed  120  /  200 epochs

Epochs completed:  72%| ███████▏   143/200 [00:18]

	completed  140  /  200 epochs

Epochs completed:  82%| ████████▏  163/200 [00:21]

	completed  160  /  200 epochs

Epochs completed:  92%| █████████▏ 183/200 [00:23]

	completed  180  /  200 epochs

Epochs completed: 100%| ██████████ 200/200 [00:26]
2026-03-10 15:56:37,659 - BERTopic - Dimensionality - Completed ✓
2026-03-10 15:56:37,660 - BERTopic - Cluster - Start clustering the reduced embeddings

Tue Mar 10 15:56:37 2026 Finished embedding

2026-03-10 15:56:46,538 - BERTopic - Cluster - Completed ✓
2026-03-10 15:56:46,545 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-03-10 15:57:20,731 - BERTopic - Representation - Completed ✓

,Topic,Count,Name,Representation,Representative_Docs
0,-1,8165,-1_memory_clean code_clean_code,"[memory, clean code, clean, code, risk, stakeh...",[Episode 28: Colin Hammond: ScopeMaster and CO...
1,0,8272,0_testing_test_selenium_automation,"[testing, test, selenium, automation, tests, m...",[Selenium Tutorial For Beginners | What Is Sel...
2,1,6525,1_devops_azure_kubernetes_cloud,"[devops, azure, kubernetes, cloud, aws, docker...","[Containerization on AWS Explained | ECS, ECR,..."
3,2,3734,2_requirements_requirement_srs_business,"[requirements, requirement, srs, business, eli...",[Understanding the BABOK Guide Structure | Exc...
4,3,2989,3_sdlc_engineering_software_architecture,"[sdlc, engineering, software, architecture, ma...",[What Software Architecture Should Look Like W...
5,4,1934,4_ai_coding_agents_claude,"[ai, coding, agents, claude, copilot, agent, a...",[Cursor AI Agents Work Like 10 Developers (Cur...
6,5,1872,5_estimation_project_chart_scheduling,"[estimation, project, chart, scheduling, manag...",[software configuration management in urdu hin...
7,6,1755,6_security_cybersecurity_vulnerabilities_privacy,"[security, cybersecurity, vulnerabilities, pri...",[What Is A Good Process For Secure Code Review...
8,7,1680,7_scrum_sprint_agile_planning,"[scrum, sprint, agile, planning, methodology, ...",[SAFe Scaled Agile Framework 5.1 for Scrum Mas...
9,8,1666,8_uml_diagram_diagrams_sequence,"[uml, diagram, diagrams, sequence, case, class...",[Sequence Diagram Tutorial and EXAMPLE | UML D...
10,9,1264,9_git_github_version_control,"[git, github, version, control, commit, branch...",[3.3.11 Lab - Software Version Control with Gi...
11,10,1240,10_debugging_errors_bugs_runtime,"[debugging, errors, bugs, runtime, error, debu...",[Will Programming Tips Improve My Ability to T...
12,11,1076,11_design_lld_low level_level,"[design, lld, low level, level, low, hld, inte...",[✅ System Design 14: Design Top K Leaderboard ...
13,12,1071,12_backend_stack_frontend_web,"[backend, stack, frontend, web, developer, bac...",[Web Development Full Course 2026 | Web Develo...
14,13,868,13_database_dbms_entity_diagram,"[database, dbms, entity, diagram, relationship...",[DBMS Lec 8 : ER Diagram practice questions wi...
15,14,693,14_reliability_sre_site_engineering,"[reliability, sre, site, engineering, failures...",[SRE Practice Test 2026 Site Reliability Engin...
16,15,606,15_stories_user_story_criteria,"[stories, user, story, criteria, agile, scrum,...",[User Stories in Agile Explained | How to Writ...
17,16,589,16_solid_principle_solid principles_principles,"[solid, principle, solid principles, principle...",[Explain the SOLID Principles The SOLID princi...
18,17,562,17_pattern_patterns_design_factory,"[pattern, patterns, design, factory, singleton...",[Java Design Pattern Interview Questions and A...
19,18,560,18_microservices_architecture_microservice_mon...,"[microservices, architecture, microservice, mo...",[Microservices Design Patterns | Microservices...
20,19,465,19_refactoring_legacy_refactor_code,"[refactoring, legacy, refactor, code, old, leg...",[rewriting legacy code by anna filina afilina ...
21,20,391,20_extreme_extreme programming_xp_programming,"[extreme, extreme programming, xp, programming...","[What Is Extreme Programming ? Hey Learner's, ..."
22,21,382,21_debt_technical debt_technical_tech debt,"[debt, technical debt, technical, tech debt, t...",[Tying technical debt to metrics that matter a...
23,22,370,22_dependency_dependencies_snippet_original,"[dependency, dependencies, snippet, original, ...",[Resolving Unknown Jar Dependency Issues in Ma...

In [37]:
topic_info = topic_model.get_topic_info()
repr_docs = topic_model.get_representative_docs()

for topic_id in topic_info.Topic:
    if topic_id == -1:
        continue
    print(f"\nTopic {topic_id}: {topic_model.get_topic(topic_id)}")
    for doc in repr_docs[topic_id]:
        print("-", doc)

Topic 0: [('testing', np.float64(0.3377778515721071)), ('test', np.float64(0.3171498019676261)), ('selenium', np.float64(0.31164538504762157)), ('automation', np.float64(0.2721564339671332)), ('tests', np.float64(0.250231909332941)), ('manual', np.float64(0.24214043740342164)), ('quality', np.float64(0.23204208838196919)), ('manual testing', np.float64(0.22682406806786268)), ('unit', np.float64(0.22317627216832914)), ('tutorial', np.float64(0.22301741285063495))]
- Selenium Tutorial For Beginners | What Is Selenium? | Selenium Automation Testing Tutorial | Edureka 🔥 Edureka Selenium Training (Use Code "𝐘𝐎𝐔𝐓𝐔𝐁𝐄𝟐𝟎"): https://www.edureka.co/selenium-certification-training This Edureka Selenium tutorial video (Selenium Blog Series: https://goo.gl/VGBJHx) will give you an introduction to software testing. It talks about the drawbacks of manual testing and reasons why automation testing is the way forward. In this Selenium tutorial, you will also get to learn the different suites of Selenium and what are the features and shortcomings of Selenium as an automation testing tool. Watch the video till the very end to witness a demonstration which shows the power of Selenium as an automation testing tool. Go through the slides in Slideshare: https://www.slideshare.net/EdurekaIN/selenium-tutorial-for-beginners-what-is-selenium-selenium-automation-testing-tutorial-edureka For doubts & queries on Selenium, post the same on Edureka Community: https://www.edureka.co/community/selenium Click on the time-stamp below to move directly to the topic you are interested in. 00:00 Introduction 02:20 Challenges with manual testing 03:32 How automation testing beats manual testing? 13:49 Selenium as an automation testing tool 20:34 Advantages & Disadvantages of Selenium 29:48 Selenium vs. QTP vs. IBM RFT 33:41 Selenium suite of tools 37:35 Hands-on: Testing a dynamic web application 🔹Selenium playlist: https://goo.gl/NmuzXE 🔹Selenium Blog List: https://bit.ly/39ZUAwR - - - - - - - - - - - - - - - - - 🔴 𝐋𝐞𝐚𝐫𝐧 𝐓𝐫𝐞𝐧𝐝𝐢𝐧𝐠 𝐓𝐞𝐜𝐡𝐧𝐨𝐥𝐨𝐠𝐢𝐞𝐬 𝐅𝐨𝐫 𝐅𝐫𝐞𝐞! 𝐒𝐮𝐛𝐬𝐜𝐫𝐢𝐛𝐞 𝐭𝐨 𝐄𝐝𝐮𝐫𝐞𝐤𝐚 𝐘𝐨𝐮𝐓𝐮𝐛𝐞 𝐂𝐡𝐚𝐧𝐧𝐞𝐥: https://edrk.in/DKQQ4Py 📢📢 𝐓𝐨𝐩 𝟏𝟎 𝐓𝐫𝐞𝐧𝐝𝐢𝐧𝐠 𝐓𝐞𝐜𝐡𝐧𝐨𝐥𝐨𝐠𝐢𝐞𝐬 𝐭𝐨 𝐋𝐞𝐚𝐫𝐧 𝐢𝐧 𝟐𝟎𝟐𝟒 𝐒𝐞𝐫𝐢𝐞𝐬 📢📢 ⏩ NEW Top 10 Technologies To Learn In 2024 - https://www.youtube.com/watch?v=vaLXPv0ewHU Instagram: https://www.instagram.com/edureka_learning Facebook: https://www.facebook.com/edurekaIN/ Twitter: https://twitter.com/edurekain LinkedIn: https://www.linkedin.com/company/edureka Telegram: https://t.me/edurekaupdates - - - - - - - - - - - - - - - - - #edureka #SeleniumEdureka #Selenium #SeleniumAutomation #SeleniumTesting #SeleniumTutorial #SeleniumTraining - - - - - - - - - - - - - - How it Works? 1. This is a 5 Week Instructor led Online Course, 20 hours of assignment and 30 hours of project work 2. We have a 24x7 One-on-One LIVE Technical Support to help you with any problems you might face or any clarifications you may require during the course. 3. At the end of the training you will have to undergo a 2-hour LIVE Practical Exam based on which we will provide you a Grade and a Verifiable Certificate! - - - - - - - - - - - - - - About the Course: Selenium is the most popular tool used to automate the testing of web applications. In this Course, you will learn about Selenium 3.0 and its various components such as Selenium IDE, Selenium WebDriver, and Selenium GRID. You learn to set up your environment so that you are ready to start using Selenium for testing your web applications. Browsers such as Chrome, Firefox, and IE are used to test the web applications. In addition, you will experience to work with Selenium IDE, Selenium WebDriver, Selenium GRID, different frameworks such as Data Driven, Keyword Driven, Hybrid and Cross browser testing. - - - - - - - - - - - - - - Who should go for this course? Selenium is a new and booming Technology in Software Industry that helps you automate the testing of your applications. Professionals with basic knowledge of Object Oriented Programming can easily take up this course. - - - - - - - - - - - - - - Why learn Selenium? For any project, Companies are rapidly inclining towards open source automated testing tools that will enable them to cut down the cost and effort that manual testing involves. Selenium is one such open source automated testing tool for websites. Performance, execution speed, and browser interaction of Selenium is too fast than any other automation tool. In addition, Selenium supports different operating systems along with support for different programming languages such as Python, Pearl, Ruby, PHP, .NET, C#, and Java; and various browsers, thereby making Selenium ahead of any other Automation tool. Customer Review: Tom Tully says, “I wanted to learn Selenium Webdriver in a live, real course, not self paced, so there would be pressure on me to finish. Edureka accomplished this at a price far lower than an in-person class, and as far as I know they are the only internet class that has live lectures on this subject. Teacher was very knowledgeable. I learned basic use of Selenium. No problem with me being in US and teacher in India. They have US 800 number.” - - - - - - - - - - - - - - For more information, Please write back to us at sales@edureka.co or call us at IND: 9606058406 / US: +18885487823 (toll free).
- Top 60 Manual Testing Interview Questions And Answers 2025 | Manual Testing Interview Questions This MindMajix video on Manual Testing Interview Questions and Answers video includes all the frequently asked Interview questions that give you an idea to crack your Manual Testing interview smartly. These Interview questions are curated by experts and will help you to brush up your knowledge in Manual Testing. This video session is designed for both beginners and professionals who want to prepare for a Manual Testing Interview. 🔥 To learn course Enroll here Manual Testing Training: https://mindmajix.com/manual-testing-training?utm_source=youtube&utm_medium=video&utm_campaign=promotion 📚 Explore more about Manual Testing from MindMajix Manual Testing blogs 👇 Manual Testing Interview Questions ➡ https://mindmajix.com/manual-testing-interview-questions Manual Testing Tutorial ➡ https://mindmajix.com/manual-testing-tutorial Types of Software Testing ➡ https://mindmajix.com/types-of-software-testing Automation Testing Vs. Manual Testing ➡ https://mindmajix.com/automation-testing-vs-manual-testing What is Spike Testing ➡ https://mindmajix.com/spike-testing 🔔 Subscribe to our channel to get video updates. https://www.youtube.com/channel/UCkKemMaRnFPlNLHZ0zOYfpA?sub_confirmation=1 🎦 Please go through this link for other Interview Questions videos: https://www.youtube.com/playlist?list=PLpnBHtRj5A6EVBhUc41Z_LS7neJDqx5_b 0:00:00 Introduction to Mindmajix 0:00:42 What do you know about Software Testing? 0:01:10 When is the ideal time to stop the process of testing? 0:02:42 Define static testing. When does static testing begin? 0:03:11 What do you mean by black-box testing? 0:03:35 What do you mean by a test plan? 0:03:56 What does the test plan include? 0:04:23 Define test coverage? 0:04:49 Can you achieve 100% testing coverage? 0:05:53 Define unit testing? 0:06:10 Define Integration testing? 0:08:59 Define exploratory testing? 0:09:24 How can you explain risk-based testing ? 0:09:51 What do you know about accessibility testing? 0:10:12 Define agile testing? 0:10:25 What is automated testing? 0:13:55 What is the use of decision table testing? 0:14:20 What are positive and negative testing? 0:14:40 What is the meaning of boundary value analysis? 0:15:19 Define the types of performance testing? 0:19:58 What is the difference between build and release? 0:20:28 What is the bug cycle? 0:20:51 State some of the bug statuses? 0:22:03 What is data-driven testing? 0:23:34 Define automation testing? 0:23:59 What are stress testing and load testing? 0:24:41 What is volume testing? 0:25:03 What are different task techniques in functional testing? 0:25:51 What is exploratory testing? 0:30:26 What would be the key challenges of manual testing? 0:31:25 Define functional and non-functional test cases? 0:31:59 What is the meaning of STLC? 0:32:29 What is the meaning of a fault? 0:32:41 State the difference between a bug, defect, and error? 0:33:04 What is the relationship between severity and priority? 0:33:30 List down the severity types? 0:34:05 Define defect removal efficiency? 0:34:36 How will you perform automated testing in an environment? 0:35:09 What is the difference between software testing, quality control, and quality assurance? 0:36:01 State the difference between bug release and bug leakage? -------------------------------------------------------------------------------------------------------- MindMajix Community: https://mindmajix.com/community Instagram: https://www.instagram.com/mindmajix/. Facebook: https://www.facebook.com/MindMajixTec... LinkedIn : https://www.linkedin.com/company/mind... Twitter: https://twitter.com/mindmajix --------------------------------------------------------------------------------------------------------------- 🟢 Manual Testing Job Roles? ✅ QA Engineers ✅ Technicians and Testers ✅ Software Developers ✅ Engineers ✅ Managers ✅ Analysts. 🟢 Why Should You Learn Manual Testing: Manual testing is a basic of all software testing types and it identifies critical bugs in the software applications. In this type of testing, the tester executes test cases without using any automation testing tools. In this manual testing course, you will learn how to test a software application manually. This manual testing online training curriculum covers all the concepts required for clearing the manual testing certification. Also this manual testing training prepares you for the roles like Quality Analyst, Manual Tester, and software tester. 🔑 Key Features : 👉 Learn from Industry Experts 👉 Gain Job-ready Skills 👉 24/7 Support 👉 Dedicated Learning Mentors 👉 Guaranteed Job Interviews 👉 Real-life Projects 👉 Get Certified 👉 Training at Feasible Time. For more information, please write back to us at info@mindmajix.com or call India : +91 905 240 3388 USA : +1 917 456 8403 Website: https://mindmajix.com #ManualTestingInterviewQuestions #ManualTestingInterviewQuestionsAndAnswers #ManualTestinginterview2025 #MindMajix #ManualTestinginterviewpreparation #ManualTestingIQ
- Cucumber Selenium Tutorial | Integrating Selenium with Cucumber BDD | Selenium Training | Edureka ** Selenium Certification Training: https://www.edureka.co/testing-with-selenium-webdriver ** This Edureka video on Cucumber Selenium Tutorial will help you understand how to integrate Cucumber with Selenium and execute the test cases. Below topics are covered in this video 1:11 - Introduction to Cucumber 2:13 - What is BDD? 3:53 - Introduction to Selenium 4:43 - Why use Cucumber with Selenium? 5:36 - Pre-requisites for using Cucumber 13:13 - Steps to create Cucumber Application Selenium playlist: https://goo.gl/NmuzXE Selenium Blog playlist: http://bit.ly/2B7C3QR - - - - - - - - - - - - - - - - - Subscribe to our channel to get video updates. Hit the subscribe button above: https://goo.gl/6ohpTV SlideShare: https://www.slideshare.net/edurekaIN Instagram: https://www.instagram.com/edureka_learning/ Facebook: https://www.facebook.com/edurekaIN/ Twitter: https://twitter.com/edurekain LinkedIn: https://www.linkedin.com/company/edureka - - - - - - - - - - - - - - - - - #edureka #edurekaselenium #cucumbersselenium #Selenium #SeleniumAutomation #SeleniumTesting #SeleniumTutorial #SeleniumTraining - - - - - - - - - - - - - - How it Works? 1. This is a 5 Week Instructor-led Online Course, 20 hours of assignment and 30 hours of project work 2. We have a 24x7 One-on-One LIVE Technical Support to help you with any problems you might face or any clarifications you may require during the course. 3. At the end of the training, you will have to undergo a 2-hour LIVE Practical Exam based on which we will provide you a Grade and a Verifiable Certificate! - - - - - - - - - - - - - - About the Course: Selenium is the most popular tool used to automate the testing of web applications. In this Course, you will learn about Selenium 3.0 and its various components such as Selenium IDE, Selenium WebDriver, and Selenium Grid. You learn to set up your environment so that you are ready to start using Selenium for testing your web applications. Browsers such as Chrome, Firefox, and IE are used to test web applications. In addition, you will experience to work with Selenium IDE, Selenium WebDriver, Selenium GRID, different frameworks such as Data Driven, Keyword Driven, Hybrid, and Cross-browser testing. Page Object Model (POM) is a design pattern that enables you to maintain reusability and readability of the automation scripts. This course introduces you to the concept of POM, and how to implement Page Classes and Page Factory to optimize the execution of automated scripts. In addition, you learn about various third-party tools such as Jenkins, TestNG, Sikuli, and AutoIT to optimally use them for performing various tasks in our browsers such as working with flash applications or Windows-based UI elements. Finally, you get introduced to Appium, an open source mobile application UI testing framework, and UIautomatorviewer. - - - - - - - - - - - - - - Who should go for this course? Selenium is a new and booming Technology in Software Industry that helps you automate the testing of your applications. Professionals with basic knowledge of Object Oriented Programming can easily take up this course. - - - - - - - - - - - - - - Why learn Selenium? For any project, Companies are rapidly inclining towards open source automated testing tools that will enable them to cut down the cost and effort that manual testing involves. Selenium is one such open source automated testing tool for websites. Performance, execution speed, and browser interaction of Selenium is too fast than any other automation tool. The test packages, the Modes of Selenium available for unattended execution, and the fact that the text script can be developed in any of the language that Selenium supports; makes Selenium the most desired automation testing tool. In addition, Selenium supports different operating systems along with support for different programming languages such as Python, Pearl, Ruby, PHP, .NET, C#, and Java; and various browsers, thereby making Selenium ahead of any other Automation tool. Customer Review: Tom Tully says, “I wanted to learn Selenium Webdriver in a live, real course, not self paced, so there would be pressure on me to finish. Edureka accomplished this at a price far lower than an in-person class, and as far as I know they are the only internet class that has live lectures on this subject. Teacher was very knowledgeable. I learned basic use of Selenium. No problem with me being in US and teacher in India. They have US 800 number.” - - - - - - - - - - - - - - For more information, Please write back to us at sales@edureka.in or call us at IND: 9606058406 / US: 18338555775 (toll free).

Topic 1: [('devops', np.float64(0.3384320271521459)), ('azure', np.float64(0.3299960795356814)), ('kubernetes', np.float64(0.32866183592982123)), ('cloud', np.float64(0.3127037334205824)), ('aws', np.float64(0.30984018265407465)), ('docker', np.float64(0.30341460581219754)), ('deployment', np.float64(0.30298201314354783)), ('azure devops', np.float64(0.2883397864812511)), ('continuous', np.float64(0.2844368309347293)), ('cicd', np.float64(0.27770750711148307))]
- Containerization on AWS Explained | ECS, ECR, EKS & App Runner (Full Deep Dive) Welcome back to another learning session! 🚀 In this video, we break down Containerization on AWS and explore how services like Amazon ECS, ECR, EKS, and App Runner help you build, deploy, scale, and manage container-based applications with ease. Whether you're a beginner stepping into containers or an experienced cloud professional designing scalable microservices — this deep-dive explainer will give you everything you need. 🔍 What You’ll Learn in This Video In this detailed walkthrough, we cover: 📦 What is Containerization? Why developers use containers Benefits of containerization (speed, portability, consistency, scaling, isolation) 🏗 AWS Container Services Overview We break down every major AWS container service: 1️⃣ Amazon ECR – Elastic Container Registry Learn how ECR helps you: Store and manage container images Integrate with CI/CD pipelines Secure images with IAM, KMS encryption, scanning & lifecycle policies Automate push/pull with Docker and AWS CLI 2️⃣ Amazon ECS – Elastic Container Service Understand in detail: ECS architecture: Task, Task Definition, Service, Cluster ECS launch types: Fargate (serverless) vs EC2 (self-managed) Auto scaling tasks based on CPU, memory, or custom CloudWatch metrics Integrating ECS with ALB, NLB, Service Discovery & IAM Roles Step-by-step request flow inside ECS 3️⃣ Amazon EKS – Elastic Kubernetes Service A complete breakdown of EKS: Kubernetes control plane vs worker nodes Pods, Deployments, Services, Ingress Node groups: managed, self-managed, Fargate Using EKS for enterprise-grade microservices When to choose EKS vs ECS Add-ons: CNI, CloudWatch, EBS CSI, Karpenter 4️⃣ AWS App Runner – Zero-Config Container Deployment Learn how App Runner helps: Deploy containers directly from GitHub or ECR Auto scale instantly (up & down) Built-in load balancing, HTTPS, monitoring No cluster management or Kubernetes complexity Ideal for small teams & simple microservices 🚀 ECS vs EKS vs App Runner (Comparison Guide) Feature ECS EKS App Runner Skill Level Easy Advanced Extremely Easy Use Case Microservices, Batch Jobs Enterprise K8s workloads Quick app hosting Management Overhead Low High Very Low Compute Options EC2 & Fargate EC2 & Fargate Fully managed Networking VPC-native VPC-native Managed Load Balancing ALB/NLB Ingress/ALB Built-in 📌 AWS Containerization Architecture Pattern We also cover a real-world architecture: Build image → Push to ECR Auto-trigger CI/CD → Deploy to ECS/EKS/App Runner Logs into CloudWatch Service scaling with CloudWatch + Application Auto Scaling Secure access using IAM roles for tasks & pods 🔐 Security Best Practices You also learn: IAM roles for tasks/pods ECR image scanning Secrets Manager for environment secrets VPC isolation for workloads Private ECR endpoints using VPC Endpoints 🎯 Who Should Watch This Video? ✔ Cloud Engineers ✔ DevOps Engineers ✔ Backend Developers ✔ Architects designing microservices ✔ Students learning AWS ✔ Anyone building scalable modern apps #AWSContainers #AWS #ECS #EKS #ECR #AppRunner #Containerization #Docker #Kubernetes #CloudComputing #AWSDevOps #DevOps #CloudNative #Microservices #Serverless #AWSFargate #ECSFargate #K8s #CICD #ImmutableInfrastructure #CloudArchitecture #AWSCloud #ContainersExplained #AWSHandsOn #TechDeepDive #LearnAWS #CloudEngineering #ModernApps #ScalableArchitecture #AWSLearning

In [48]:
from collections import defaultdict

topic_to_ids = defaultdict(list)

for doc_id, topic in zip(ids, topics):
    topic_to_ids[topic].append(doc_id)

In [49]:
topic_to_docs = defaultdict(list)

for doc_id, doc, topic in zip(ids, documents, topics):
    topic_to_docs[topic].append({
        "id": doc_id,
        "text": doc
    })

In [ ]:
df2 = pd.DataFrame({
    "id": ids,
    "document": documents,
    "topic": topics
})

In [56]:
df_sorted = df2.sort_values(by="topic")[["topic", "id", "document"]]

df_sorted.to_csv(f"{output_dir}/topic_documents.csv", index=False)

In [38]:
topic_model.save(f'{output_dir}/bt_48k_1003.model')
topic_model.save(f'{output_dir}/bt_48k_1003.pickle', serialization="pickle")

2026-03-10 15:57:44,531 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Tue Mar 10 15:57:45 2026 Building hub-based search tree
Tue Mar 10 15:57:45 2026 Forward diversification reduced edges from 730935 to 217455
Tue Mar 10 15:57:45 2026 Reverse diversification reduced edges from 217455 to 217455
Tue Mar 10 15:57:45 2026 Degree pruning reduced edges from 239100 to 239045
Tue Mar 10 15:57:45 2026 Resorting data and graph based on tree order
Tue Mar 10 15:57:45 2026 Building and compiling search function

2026-03-10 15:57:47,727 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

# Find Best Params

In [10]:
def compute_cv(topic_model, docs, top_n=10):
    texts = [simple_preprocess(doc) for doc in docs]
    dictionary = Dictionary(texts)
    
    topics = []
    for topic_id, words in topic_model.get_topics().items():
        if topic_id == -1:
            continue
        topics.append([w for w, _ in words[:top_n]])

    if len(topics) < 2:
        return None

    cm = CoherenceModel(
        topics=topics,
        texts=texts,
        dictionary=dictionary,
        coherence="c_v"
    )
    return cm.get_coherence()

In [13]:
def check(min_cluster_size, docs, embd):
    hdbscan_model = HDBSCAN(min_cluster_size=min_cluster_size, prediction_data=True)
    ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)
    vectorizer_model = CountVectorizer(stop_words= "english", ngram_range=(1, 3), min_df=10)
    representation_model = [PartOfSpeech("en_core_web_sm"), MaximalMarginalRelevance(diversity=0.3)]
    umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.01, metric='cosine', random_state=random_seed, verbose=True)

    model = BERTopic(
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer_model,
        ctfidf_model=ctfidf_model,
        representation_model=representation_model,
        calculate_probabilities=False,
        top_n_words=20,
        verbose=False,
    )
    model.fit_transform(docs, embeddings=embd)
    score = compute_cv(model, docs)

    print("-"*50)
    print(f"Number of topics: {len(model.get_topics())}")
    print(f"Coherence score for {min_cluster_size}: {score}")
    print("-"*50)
    return score

In [14]:
sizes = [100, 150, 200, 250, 300, 350, 400, 450, 500]

for size in sizes:
    check(size, documents, embeddings)

UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.01, n_components=5, n_jobs=1, random_state=42, verbose=True)
Mon Mar 16 18:04:11 2026 Construct fuzzy simplicial set
Mon Mar 16 18:04:12 2026 Finding Nearest Neighbors
Mon Mar 16 18:04:12 2026 Building RP forest with 18 trees
Mon Mar 16 18:04:14 2026 NN descent for 16 iterations
	 1  /  16
	 2  /  16
	 3  /  16
	 4  /  16
	Stopping threshold met -- exiting after 4 iterations
Mon Mar 16 18:04:20 2026 Finished Nearest Neighbor Search
Mon Mar 16 18:04:20 2026 Construct embedding

Epochs completed:   2%| ▏          3/200 [00:00]

	completed  0  /  200 epochs

Epochs completed:  12%| █▏         23/200 [00:03]

	completed  20  /  200 epochs

Epochs completed:  22%| ██▏        43/200 [00:06]

	completed  40  /  200 epochs

Epochs completed:  32%| ███▏       63/200 [00:10]

	completed  60  /  200 epochs

Epochs completed:  42%| ████▏      83/200 [00:13]

	completed  80  /  200 epochs

Epochs completed:  52%| █████▏     103/200 [00:17]

	completed  100  /  200 epochs

Epochs completed:  62%| ██████▏    123/200 [00:20]

	completed  120  /  200 epochs

Epochs completed:  72%| ███████▏   143/200 [00:24]

	completed  140  /  200 epochs

Epochs completed:  82%| ████████▏  163/200 [00:27]

	completed  160  /  200 epochs

Epochs completed:  92%| █████████▏ 183/200 [00:30]

	completed  180  /  200 epochs

Epochs completed: 100%| ██████████ 200/200 [00:33]

Mon Mar 16 18:05:01 2026 Finished embedding
--------------------------------------------------
Number of topics: 110
Coherence score for 100: 0.6976862417995335
--------------------------------------------------
UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.01, n_components=5, n_jobs=1, random_state=42, verbose=True)
Mon Mar 16 18:07:32 2026 Construct fuzzy simplicial set
Mon Mar 16 18:07:32 2026 Finding Nearest Neighbors
Mon Mar 16 18:07:32 2026 Building RP forest with 18 trees
Mon Mar 16 18:07:35 2026 NN descent for 16 iterations
	 1  /  16
	 2  /  16
	 3  /  16
	 4  /  16
	Stopping threshold met -- exiting after 4 iterations
Mon Mar 16 18:07:41 2026 Finished Nearest Neighbor Search
Mon Mar 16 18:07:41 2026 Construct embedding

Epochs completed:   2%| ▎          5/200 [00:00]

	completed  0  /  200 epochs

Epochs completed:  11%| █          22/200 [00:03]

	completed  20  /  200 epochs

Epochs completed:  22%| ██▏        43/200 [00:06]

	completed  40  /  200 epochs

Epochs completed:  32%| ███▏       63/200 [00:10]

	completed  60  /  200 epochs

Epochs completed:  42%| ████▏      83/200 [00:13]

	completed  80  /  200 epochs

Epochs completed:  52%| █████▏     103/200 [00:17]

	completed  100  /  200 epochs

Epochs completed:  62%| ██████▏    123/200 [00:20]

	completed  120  /  200 epochs

Epochs completed:  72%| ███████▏   143/200 [00:24]

	completed  140  /  200 epochs

Epochs completed:  82%| ████████▏  163/200 [00:27]

	completed  160  /  200 epochs

Epochs completed:  92%| █████████▏ 183/200 [00:31]

	completed  180  /  200 epochs

Epochs completed: 100%| ██████████ 200/200 [00:34]

Mon Mar 16 18:08:22 2026 Finished embedding
--------------------------------------------------
Number of topics: 80
Coherence score for 150: 0.7099120028365687
--------------------------------------------------
UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.01, n_components=5, n_jobs=1, random_state=42, verbose=True)
Mon Mar 16 18:10:29 2026 Construct fuzzy simplicial set
Mon Mar 16 18:10:29 2026 Finding Nearest Neighbors
Mon Mar 16 18:10:29 2026 Building RP forest with 18 trees
Mon Mar 16 18:10:31 2026 NN descent for 16 iterations
	 1  /  16
	 2  /  16
	 3  /  16
	 4  /  16
	Stopping threshold met -- exiting after 4 iterations
Mon Mar 16 18:10:38 2026 Finished Nearest Neighbor Search
Mon Mar 16 18:10:38 2026 Construct embedding

Epochs completed:   2%| ▏          3/200 [00:00]

	completed  0  /  200 epochs

Epochs completed:  12%| █▏         23/200 [00:03]

	completed  20  /  200 epochs

Epochs completed:  22%| ██▏        43/200 [00:06]

	completed  40  /  200 epochs

Epochs completed:  32%| ███▏       63/200 [00:10]

	completed  60  /  200 epochs

Epochs completed:  42%| ████▏      83/200 [00:13]

	completed  80  /  200 epochs

Epochs completed:  52%| █████▏     103/200 [00:17]

	completed  100  /  200 epochs

Epochs completed:  61%| ██████     122/200 [00:20]

	completed  120  /  200 epochs

Epochs completed:  72%| ███████▏   143/200 [00:24]

	completed  140  /  200 epochs

Epochs completed:  82%| ████████▏  163/200 [00:27]

	completed  160  /  200 epochs

Epochs completed:  92%| █████████▏ 183/200 [00:31]

	completed  180  /  200 epochs

Epochs completed: 100%| ██████████ 200/200 [00:34]

Mon Mar 16 18:11:19 2026 Finished embedding
--------------------------------------------------
Number of topics: 66
Coherence score for 200: 0.7092933553601154
--------------------------------------------------
UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.01, n_components=5, n_jobs=1, random_state=42, verbose=True)
Mon Mar 16 18:13:16 2026 Construct fuzzy simplicial set
Mon Mar 16 18:13:16 2026 Finding Nearest Neighbors
Mon Mar 16 18:13:16 2026 Building RP forest with 18 trees
Mon Mar 16 18:13:18 2026 NN descent for 16 iterations
	 1  /  16
	 2  /  16
	 3  /  16
	 4  /  16
	Stopping threshold met -- exiting after 4 iterations
Mon Mar 16 18:13:24 2026 Finished Nearest Neighbor Search
Mon Mar 16 18:13:25 2026 Construct embedding

Epochs completed:   2%| ▎          5/200 [00:00]

	completed  0  /  200 epochs

Epochs completed:  12%| █▏         23/200 [00:03]

	completed  20  /  200 epochs

Epochs completed:  22%| ██▏        43/200 [00:06]

	completed  40  /  200 epochs

Epochs completed:  32%| ███▏       63/200 [00:10]

	completed  60  /  200 epochs

Epochs completed:  42%| ████▏      83/200 [00:13]

	completed  80  /  200 epochs

Epochs completed:  52%| █████▏     103/200 [00:17]

	completed  100  /  200 epochs

Epochs completed:  62%| ██████▏    123/200 [00:20]

	completed  120  /  200 epochs

Epochs completed:  72%| ███████▏   143/200 [00:24]

	completed  140  /  200 epochs

Epochs completed:  82%| ████████▏  163/200 [00:27]

	completed  160  /  200 epochs

Epochs completed:  91%| █████████  182/200 [00:31]

	completed  180  /  200 epochs

Epochs completed: 100%| ██████████ 200/200 [00:34]

Mon Mar 16 18:14:06 2026 Finished embedding
--------------------------------------------------
Number of topics: 55
Coherence score for 250: 0.7328467871584498
--------------------------------------------------
UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.01, n_components=5, n_jobs=1, random_state=42, verbose=True)
Mon Mar 16 18:15:51 2026 Construct fuzzy simplicial set
Mon Mar 16 18:15:51 2026 Finding Nearest Neighbors
Mon Mar 16 18:15:51 2026 Building RP forest with 18 trees
Mon Mar 16 18:15:53 2026 NN descent for 16 iterations
	 1  /  16
	 2  /  16
	 3  /  16
	 4  /  16
	Stopping threshold met -- exiting after 4 iterations
Mon Mar 16 18:16:00 2026 Finished Nearest Neighbor Search
Mon Mar 16 18:16:00 2026 Construct embedding

Epochs completed:   2%| ▎          5/200 [00:00]

	completed  0  /  200 epochs

Epochs completed:  12%| █▏         23/200 [00:03]

	completed  20  /  200 epochs

Epochs completed:  22%| ██▏        43/200 [00:06]

	completed  40  /  200 epochs

Epochs completed:  32%| ███▏       63/200 [00:10]

	completed  60  /  200 epochs

Epochs completed:  42%| ████▏      83/200 [00:13]

	completed  80  /  200 epochs

Epochs completed:  52%| █████▏     103/200 [00:17]

	completed  100  /  200 epochs

Epochs completed:  61%| ██████     122/200 [00:20]

	completed  120  /  200 epochs

Epochs completed:  72%| ███████▏   143/200 [00:24]

	completed  140  /  200 epochs

Epochs completed:  82%| ████████▏  163/200 [00:27]

	completed  160  /  200 epochs

Epochs completed:  92%| █████████▏ 183/200 [00:31]

	completed  180  /  200 epochs

Epochs completed: 100%| ██████████ 200/200 [00:34]

Mon Mar 16 18:16:41 2026 Finished embedding
--------------------------------------------------
Number of topics: 38
Coherence score for 300: 0.72876748128715
--------------------------------------------------
UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.01, n_components=5, n_jobs=1, random_state=42, verbose=True)
Mon Mar 16 18:18:11 2026 Construct fuzzy simplicial set
Mon Mar 16 18:18:11 2026 Finding Nearest Neighbors
Mon Mar 16 18:18:11 2026 Building RP forest with 18 trees
Mon Mar 16 18:18:14 2026 NN descent for 16 iterations
	 1  /  16
	 2  /  16
	 3  /  16
	 4  /  16
	Stopping threshold met -- exiting after 4 iterations
Mon Mar 16 18:18:20 2026 Finished Nearest Neighbor Search
Mon Mar 16 18:18:20 2026 Construct embedding

Epochs completed:   2%| ▏          3/200 [00:00]

	completed  0  /  200 epochs

Epochs completed:  12%| █▏         23/200 [00:03]

	completed  20  /  200 epochs

Epochs completed:  22%| ██▏        43/200 [00:06]

	completed  40  /  200 epochs

Epochs completed:  32%| ███▏       63/200 [00:09]

	completed  60  /  200 epochs

Epochs completed:  42%| ████▏      83/200 [00:13]

	completed  80  /  200 epochs

Epochs completed:  52%| █████▏     103/200 [00:16]

	completed  100  /  200 epochs

Epochs completed:  62%| ██████▏    123/200 [00:19]

	completed  120  /  200 epochs

Epochs completed:  72%| ███████▏   143/200 [00:23]

	completed  140  /  200 epochs

Epochs completed:  82%| ████████▏  163/200 [00:26]

	completed  160  /  200 epochs

Epochs completed:  92%| █████████▏ 183/200 [00:29]

	completed  180  /  200 epochs

Epochs completed: 100%| ██████████ 200/200 [00:32]

Mon Mar 16 18:19:00 2026 Finished embedding
--------------------------------------------------
Number of topics: 35
Coherence score for 350: 0.7437750957278528
--------------------------------------------------
UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.01, n_components=5, n_jobs=1, random_state=42, verbose=True)
Mon Mar 16 18:20:28 2026 Construct fuzzy simplicial set
Mon Mar 16 18:20:28 2026 Finding Nearest Neighbors
Mon Mar 16 18:20:28 2026 Building RP forest with 18 trees
Mon Mar 16 18:20:30 2026 NN descent for 16 iterations
	 1  /  16
	 2  /  16
	 3  /  16
	 4  /  16
	Stopping threshold met -- exiting after 4 iterations
Mon Mar 16 18:20:36 2026 Finished Nearest Neighbor Search
Mon Mar 16 18:20:37 2026 Construct embedding

Epochs completed:   2%| ▏          3/200 [00:00]

	completed  0  /  200 epochs

Epochs completed:  11%| █          22/200 [00:03]

	completed  20  /  200 epochs

Epochs completed:  22%| ██▏        43/200 [00:06]

	completed  40  /  200 epochs

Epochs completed:  32%| ███▏       63/200 [00:10]

	completed  60  /  200 epochs

Epochs completed:  42%| ████▏      83/200 [00:13]

	completed  80  /  200 epochs

Epochs completed:  52%| █████▏     103/200 [00:17]

	completed  100  /  200 epochs

Epochs completed:  62%| ██████▏    123/200 [00:20]

	completed  120  /  200 epochs

Epochs completed:  72%| ███████▏   143/200 [00:24]

	completed  140  /  200 epochs

Epochs completed:  82%| ████████▏  163/200 [00:27]

	completed  160  /  200 epochs

Epochs completed:  92%| █████████▏ 183/200 [00:31]

	completed  180  /  200 epochs

Epochs completed: 100%| ██████████ 200/200 [00:34]

Mon Mar 16 18:21:17 2026 Finished embedding
--------------------------------------------------
Number of topics: 26
Coherence score for 400: 0.7484781140821721
--------------------------------------------------
UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.01, n_components=5, n_jobs=1, random_state=42, verbose=True)
Mon Mar 16 18:22:35 2026 Construct fuzzy simplicial set
Mon Mar 16 18:22:35 2026 Finding Nearest Neighbors
Mon Mar 16 18:22:35 2026 Building RP forest with 18 trees
Mon Mar 16 18:22:37 2026 NN descent for 16 iterations
	 1  /  16
	 2  /  16
	 3  /  16
	 4  /  16
	Stopping threshold met -- exiting after 4 iterations
Mon Mar 16 18:22:44 2026 Finished Nearest Neighbor Search
Mon Mar 16 18:22:44 2026 Construct embedding

Epochs completed:   2%| ▏          3/200 [00:00]

	completed  0  /  200 epochs

Epochs completed:  12%| █▏         23/200 [00:03]

	completed  20  /  200 epochs

Epochs completed:  21%| ██         42/200 [00:06]

	completed  40  /  200 epochs

Epochs completed:  32%| ███▏       63/200 [00:10]

	completed  60  /  200 epochs

Epochs completed:  42%| ████▏      83/200 [00:13]

	completed  80  /  200 epochs

Epochs completed:  52%| █████▏     103/200 [00:17]

	completed  100  /  200 epochs

Epochs completed:  62%| ██████▏    123/200 [00:20]

	completed  120  /  200 epochs

Epochs completed:  72%| ███████▏   143/200 [00:24]

	completed  140  /  200 epochs

Epochs completed:  82%| ████████▏  163/200 [00:27]

	completed  160  /  200 epochs

Epochs completed:  92%| █████████▏ 183/200 [00:31]

	completed  180  /  200 epochs

Epochs completed: 100%| ██████████ 200/200 [00:34]

Mon Mar 16 18:23:25 2026 Finished embedding
--------------------------------------------------
Number of topics: 23
Coherence score for 450: 0.7622870675099332
--------------------------------------------------
UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.01, n_components=5, n_jobs=1, random_state=42, verbose=True)
Mon Mar 16 18:24:40 2026 Construct fuzzy simplicial set
Mon Mar 16 18:24:41 2026 Finding Nearest Neighbors
Mon Mar 16 18:24:41 2026 Building RP forest with 18 trees
Mon Mar 16 18:24:43 2026 NN descent for 16 iterations
	 1  /  16
	 2  /  16
	 3  /  16
	 4  /  16
	Stopping threshold met -- exiting after 4 iterations
Mon Mar 16 18:24:49 2026 Finished Nearest Neighbor Search
Mon Mar 16 18:24:49 2026 Construct embedding

Epochs completed:   2%| ▎          5/200 [00:00]

	completed  0  /  200 epochs

Epochs completed:  11%| █          22/200 [00:03]

	completed  20  /  200 epochs

Epochs completed:  22%| ██▏        43/200 [00:07]

	completed  40  /  200 epochs

Epochs completed:  32%| ███▏       63/200 [00:10]

	completed  60  /  200 epochs

Epochs completed:  42%| ████▏      83/200 [00:14]

	completed  80  /  200 epochs

Epochs completed:  51%| █████      102/200 [00:17]

	completed  100  /  200 epochs

Epochs completed:  62%| ██████▏    123/200 [00:20]

	completed  120  /  200 epochs

Epochs completed:  72%| ███████▏   143/200 [00:24]

	completed  140  /  200 epochs

Epochs completed:  82%| ████████▏  163/200 [00:27]

	completed  160  /  200 epochs

Epochs completed:  92%| █████████▏ 183/200 [00:30]

	completed  180  /  200 epochs

Epochs completed: 100%| ██████████ 200/200 [00:33]

Mon Mar 16 18:25:30 2026 Finished embedding
--------------------------------------------------
Number of topics: 21
Coherence score for 500: 0.7670260216144841
--------------------------------------------------

# Final Topic Discovery

## Apply BERTopic

Best params:
- min_cluster_size: 350

In [5]:
embeddings = np.load(f"{output_dir}/embeddings.npy")

In [7]:
hdbscan_model = HDBSCAN(min_cluster_size=350, prediction_data=True)
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)
vectorizer_model = CountVectorizer(stop_words= "english", ngram_range=(1, 3), min_df=10)
representation_model = [PartOfSpeech("en_core_web_sm"), MaximalMarginalRelevance(diversity=0.3)]
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.01, metric='cosine', random_state=random_seed, verbose=True)

model = BERTopic(
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
    representation_model=representation_model,
    calculate_probabilities=False,
    top_n_words=10,
    verbose=False,
)

In [8]:
topics, probs = model.fit_transform(documents, embeddings=embeddings)
model.get_topic_info()

UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.01, n_components=5, n_jobs=1, random_state=42, verbose=True)
Thu Mar 12 12:00:54 2026 Construct fuzzy simplicial set
Thu Mar 12 12:00:54 2026 Finding Nearest Neighbors
Thu Mar 12 12:00:54 2026 Building RP forest with 16 trees

/home/cs/grad/mazumdmm/Masud/YouTube Project/YouTube-4SE/.venv/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:373: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.
  warnings.warn(problem)

Thu Mar 12 12:01:00 2026 NN descent for 16 iterations
	 1  /  16
	 2  /  16
	 3  /  16
	 4  /  16
	Stopping threshold met -- exiting after 4 iterations
Thu Mar 12 12:01:13 2026 Finished Nearest Neighbor Search
Thu Mar 12 12:01:15 2026 Construct embedding

Epochs completed:   2%| ▎          5/200 [00:00]

	completed  0  /  200 epochs

Epochs completed:  12%| █▏         23/200 [00:03]

	completed  20  /  200 epochs

Epochs completed:  22%| ██▏        43/200 [00:05]

	completed  40  /  200 epochs

Epochs completed:  32%| ███▏       63/200 [00:08]

	completed  60  /  200 epochs

Epochs completed:  41%| ████       82/200 [00:11]

	completed  80  /  200 epochs

Epochs completed:  52%| █████▏     103/200 [00:13]

	completed  100  /  200 epochs

Epochs completed:  62%| ██████▏    123/200 [00:16]

	completed  120  /  200 epochs

Epochs completed:  72%| ███████▏   143/200 [00:19]

	completed  140  /  200 epochs

Epochs completed:  82%| ████████▏  163/200 [00:21]

	completed  160  /  200 epochs

Epochs completed:  92%| █████████▏ 183/200 [00:24]

	completed  180  /  200 epochs

Epochs completed: 100%| ██████████ 200/200 [00:26]

Thu Mar 12 12:01:45 2026 Finished embedding

,Topic,Count,Name,Representation,Representative_Docs
0,-1,8165,-1_memory_clean code_clean_code,"[memory, clean code, clean, code, risk, handli...",[Episode 28: Colin Hammond: ScopeMaster and CO...
1,0,8272,0_testing_test_selenium_automation,"[testing, test, selenium, automation, tests, m...",[Selenium Tutorial For Beginners | What Is Sel...
2,1,6525,1_devops_azure_kubernetes_cloud,"[devops, azure, kubernetes, cloud, aws, docker...",[What Is A Build Server In Continuous Integrat...
3,2,3734,2_requirements_requirement_srs_business,"[requirements, requirement, srs, business, eli...",[Understanding the BABOK Guide Structure | Exc...
4,3,2989,3_sdlc_engineering_software_architecture,"[sdlc, engineering, software, architecture, ma...",[Introduction to Software Engineering Part 1 A...
5,4,1934,4_ai_coding_agents_claude,"[ai, coding, agents, claude, copilot, agent, a...",[Cursor AI Agents Work Like 10 Developers (Cur...
6,5,1872,5_estimation_project_chart_scheduling,"[estimation, project, chart, scheduling, manag...",[Software Project Management Week 10 | NPTEL A...
7,6,1755,6_security_cybersecurity_vulnerabilities_privacy,"[security, cybersecurity, vulnerabilities, pri...",[What Is A Good Process For Secure Code Review...
8,7,1680,7_scrum_sprint_agile_planning,"[scrum, sprint, agile, planning, methodology, ...",[SAFe Scaled Agile Framework 5.1 for Scrum Mas...
9,8,1666,8_uml_diagram_diagrams_sequence,"[uml, diagram, diagrams, sequence, case, class...",[Sequence Diagram Tutorial and EXAMPLE | UML D...
10,9,1264,9_git_github_version_control,"[git, github, version, control, commit, branch...",[Git Log Command Explained with Options and Ex...
11,10,1240,10_debugging_errors_bugs_runtime,"[debugging, errors, bugs, runtime, error, debu...",[Will Programming Tips Improve My Ability to T...
12,11,1076,11_design_lld_low level_level,"[design, lld, low level, level, low, hld, inte...",[What is Low Level System Design | System Arch...
13,12,1071,12_backend_stack_frontend_web,"[backend, stack, frontend, web, developer, bac...",[Web Development Full Course 2026 | Web Develo...
14,13,868,13_database_dbms_diagram_entity,"[database, dbms, diagram, entity, relationship...",[DBMS Lec 8 : ER Diagram practice questions wi...
15,14,693,14_reliability_sre_site_engineering,"[reliability, sre, site, engineering, failures...",[SRE Practice Test 2026 Site Reliability Engin...
16,15,606,15_stories_user_story_criteria,"[stories, user, story, criteria, agile, scrum,...",[User Stories and Acceptance Criteria | Simpli...
17,16,589,16_solid_principle_solid principles_principles,"[solid, principle, solid principles, principle...",[Explain the SOLID Principles The SOLID princi...
18,17,562,17_pattern_patterns_design_factory,"[pattern, patterns, design, factory, singleton...",[Java Design Pattern Interview Questions and A...
19,18,560,18_microservices_architecture_microservice_mon...,"[microservices, architecture, microservice, mo...",[Microservices Design Patterns | Microservices...
20,19,465,19_refactoring_legacy_code_refactor,"[refactoring, legacy, code, refactor, old, leg...",[rewriting legacy code by anna filina afilina ...
21,20,391,20_extreme_extreme programming_xp_programming,"[extreme, extreme programming, xp, programming...","[XP Model: Introduction, Core Values, Roles, P..."
22,21,382,21_debt_technical debt_technical_tech debt,"[debt, technical debt, technical, tech debt, t...",[How to manage technical debt with Lou Franco ...
23,22,370,22_dependency_dependencies_snippet_original,"[dependency, dependencies, snippet, original, ...",[Resolving Dependency Conflicts in Maven Learn...

## Analyze

In [11]:
topic_info = model.get_topic_info()
repr_docs = model.get_representative_docs()

for topic_id in topic_info.Topic:
    if topic_id == -1:
        continue
    print(f"\nTopic {topic_id}: {model.get_topic(topic_id)}")
    for doc in repr_docs[topic_id]:
        print("-", doc)

Topic 0: [('testing', np.float64(0.33764887537480565)), ('test', np.float64(0.31588205778385303)), ('selenium', np.float64(0.30985742709073255)), ('automation', np.float64(0.27069511536123214)), ('tests', np.float64(0.24840719337361677)), ('manual', np.float64(0.24027138843119725)), ('quality', np.float64(0.23051227087694276)), ('manual testing', np.float64(0.22482787348826302)), ('tutorial', np.float64(0.22207798968127848)), ('unit', np.float64(0.22138717677362915))]
- Selenium Tutorial For Beginners | What Is Selenium? | Selenium Automation Testing Tutorial | Edureka 🔥 Edureka Selenium Training (Use Code "𝐘𝐎𝐔𝐓𝐔𝐁𝐄𝟐𝟎"): https://www.edureka.co/selenium-certification-training This Edureka Selenium tutorial video (Selenium Blog Series: https://goo.gl/VGBJHx) will give you an introduction to software testing. It talks about the drawbacks of manual testing and reasons why automation testing is the way forward. In this Selenium tutorial, you will also get to learn the different suites of Selenium and what are the features and shortcomings of Selenium as an automation testing tool. Watch the video till the very end to witness a demonstration which shows the power of Selenium as an automation testing tool. Go through the slides in Slideshare: https://www.slideshare.net/EdurekaIN/selenium-tutorial-for-beginners-what-is-selenium-selenium-automation-testing-tutorial-edureka For doubts & queries on Selenium, post the same on Edureka Community: https://www.edureka.co/community/selenium Click on the time-stamp below to move directly to the topic you are interested in. 00:00 Introduction 02:20 Challenges with manual testing 03:32 How automation testing beats manual testing? 13:49 Selenium as an automation testing tool 20:34 Advantages & Disadvantages of Selenium 29:48 Selenium vs. QTP vs. IBM RFT 33:41 Selenium suite of tools 37:35 Hands-on: Testing a dynamic web application 🔹Selenium playlist: https://goo.gl/NmuzXE 🔹Selenium Blog List: https://bit.ly/39ZUAwR - - - - - - - - - - - - - - - - - 🔴 𝐋𝐞𝐚𝐫𝐧 𝐓𝐫𝐞𝐧𝐝𝐢𝐧𝐠 𝐓𝐞𝐜𝐡𝐧𝐨𝐥𝐨𝐠𝐢𝐞𝐬 𝐅𝐨𝐫 𝐅𝐫𝐞𝐞! 𝐒𝐮𝐛𝐬𝐜𝐫𝐢𝐛𝐞 𝐭𝐨 𝐄𝐝𝐮𝐫𝐞𝐤𝐚 𝐘𝐨𝐮𝐓𝐮𝐛𝐞 𝐂𝐡𝐚𝐧𝐧𝐞𝐥: https://edrk.in/DKQQ4Py 📢📢 𝐓𝐨𝐩 𝟏𝟎 𝐓𝐫𝐞𝐧𝐝𝐢𝐧𝐠 𝐓𝐞𝐜𝐡𝐧𝐨𝐥𝐨𝐠𝐢𝐞𝐬 𝐭𝐨 𝐋𝐞𝐚𝐫𝐧 𝐢𝐧 𝟐𝟎𝟐𝟒 𝐒𝐞𝐫𝐢𝐞𝐬 📢📢 ⏩ NEW Top 10 Technologies To Learn In 2024 - https://www.youtube.com/watch?v=vaLXPv0ewHU Instagram: https://www.instagram.com/edureka_learning Facebook: https://www.facebook.com/edurekaIN/ Twitter: https://twitter.com/edurekain LinkedIn: https://www.linkedin.com/company/edureka Telegram: https://t.me/edurekaupdates - - - - - - - - - - - - - - - - - #edureka #SeleniumEdureka #Selenium #SeleniumAutomation #SeleniumTesting #SeleniumTutorial #SeleniumTraining - - - - - - - - - - - - - - How it Works? 1. This is a 5 Week Instructor led Online Course, 20 hours of assignment and 30 hours of project work 2. We have a 24x7 One-on-One LIVE Technical Support to help you with any problems you might face or any clarifications you may require during the course. 3. At the end of the training you will have to undergo a 2-hour LIVE Practical Exam based on which we will provide you a Grade and a Verifiable Certificate! - - - - - - - - - - - - - - About the Course: Selenium is the most popular tool used to automate the testing of web applications. In this Course, you will learn about Selenium 3.0 and its various components such as Selenium IDE, Selenium WebDriver, and Selenium GRID. You learn to set up your environment so that you are ready to start using Selenium for testing your web applications. Browsers such as Chrome, Firefox, and IE are used to test the web applications. In addition, you will experience to work with Selenium IDE, Selenium WebDriver, Selenium GRID, different frameworks such as Data Driven, Keyword Driven, Hybrid and Cross browser testing. - - - - - - - - - - - - - - Who should go for this course? Selenium is a new and booming Technology in Software Industry that helps you automate the testing of your applications. Professionals with basic knowledge of Object Oriented Programming can easily take up this course. - - - - - - - - - - - - - - Why learn Selenium? For any project, Companies are rapidly inclining towards open source automated testing tools that will enable them to cut down the cost and effort that manual testing involves. Selenium is one such open source automated testing tool for websites. Performance, execution speed, and browser interaction of Selenium is too fast than any other automation tool. In addition, Selenium supports different operating systems along with support for different programming languages such as Python, Pearl, Ruby, PHP, .NET, C#, and Java; and various browsers, thereby making Selenium ahead of any other Automation tool. Customer Review: Tom Tully says, “I wanted to learn Selenium Webdriver in a live, real course, not self paced, so there would be pressure on me to finish. Edureka accomplished this at a price far lower than an in-person class, and as far as I know they are the only internet class that has live lectures on this subject. Teacher was very knowledgeable. I learned basic use of Selenium. No problem with me being in US and teacher in India. They have US 800 number.” - - - - - - - - - - - - - - For more information, Please write back to us at sales@edureka.co or call us at IND: 9606058406 / US: +18885487823 (toll free).
- Top 60 Manual Testing Interview Questions And Answers 2025 | Manual Testing Interview Questions This MindMajix video on Manual Testing Interview Questions and Answers video includes all the frequently asked Interview questions that give you an idea to crack your Manual Testing interview smartly. These Interview questions are curated by experts and will help you to brush up your knowledge in Manual Testing. This video session is designed for both beginners and professionals who want to prepare for a Manual Testing Interview. 🔥 To learn course Enroll here Manual Testing Training: https://mindmajix.com/manual-testing-training?utm_source=youtube&utm_medium=video&utm_campaign=promotion 📚 Explore more about Manual Testing from MindMajix Manual Testing blogs 👇 Manual Testing Interview Questions ➡ https://mindmajix.com/manual-testing-interview-questions Manual Testing Tutorial ➡ https://mindmajix.com/manual-testing-tutorial Types of Software Testing ➡ https://mindmajix.com/types-of-software-testing Automation Testing Vs. Manual Testing ➡ https://mindmajix.com/automation-testing-vs-manual-testing What is Spike Testing ➡ https://mindmajix.com/spike-testing 🔔 Subscribe to our channel to get video updates. https://www.youtube.com/channel/UCkKemMaRnFPlNLHZ0zOYfpA?sub_confirmation=1 🎦 Please go through this link for other Interview Questions videos: https://www.youtube.com/playlist?list=PLpnBHtRj5A6EVBhUc41Z_LS7neJDqx5_b 0:00:00 Introduction to Mindmajix 0:00:42 What do you know about Software Testing? 0:01:10 When is the ideal time to stop the process of testing? 0:02:42 Define static testing. When does static testing begin? 0:03:11 What do you mean by black-box testing? 0:03:35 What do you mean by a test plan? 0:03:56 What does the test plan include? 0:04:23 Define test coverage? 0:04:49 Can you achieve 100% testing coverage? 0:05:53 Define unit testing? 0:06:10 Define Integration testing? 0:08:59 Define exploratory testing? 0:09:24 How can you explain risk-based testing ? 0:09:51 What do you know about accessibility testing? 0:10:12 Define agile testing? 0:10:25 What is automated testing? 0:13:55 What is the use of decision table testing? 0:14:20 What are positive and negative testing? 0:14:40 What is the meaning of boundary value analysis? 0:15:19 Define the types of performance testing? 0:19:58 What is the difference between build and release? 0:20:28 What is the bug cycle? 0:20:51 State some of the bug statuses? 0:22:03 What is data-driven testing? 0:23:34 Define automation testing? 0:23:59 What are stress testing and load testing? 0:24:41 What is volume testing? 0:25:03 What are different task techniques in functional testing? 0:25:51 What is exploratory testing? 0:30:26 What would be the key challenges of manual testing? 0:31:25 Define functional and non-functional test cases? 0:31:59 What is the meaning of STLC? 0:32:29 What is the meaning of a fault? 0:32:41 State the difference between a bug, defect, and error? 0:33:04 What is the relationship between severity and priority? 0:33:30 List down the severity types? 0:34:05 Define defect removal efficiency? 0:34:36 How will you perform automated testing in an environment? 0:35:09 What is the difference between software testing, quality control, and quality assurance? 0:36:01 State the difference between bug release and bug leakage? -------------------------------------------------------------------------------------------------------- MindMajix Community: https://mindmajix.com/community Instagram: https://www.instagram.com/mindmajix/. Facebook: https://www.facebook.com/MindMajixTec... LinkedIn : https://www.linkedin.com/company/mind... Twitter: https://twitter.com/mindmajix --------------------------------------------------------------------------------------------------------------- 🟢 Manual Testing Job Roles? ✅ QA Engineers ✅ Technicians and Testers ✅ Software Developers ✅ Engineers ✅ Managers ✅ Analysts. 🟢 Why Should You Learn Manual Testing: Manual testing is a basic of all software testing types and it identifies critical bugs in the software applications. In this type of testing, the tester executes test cases without using any automation testing tools. In this manual testing course, you will learn how to test a software application manually. This manual testing online training curriculum covers all the concepts required for clearing the manual testing certification. Also this manual testing training prepares you for the roles like Quality Analyst, Manual Tester, and software tester. 🔑 Key Features : 👉 Learn from Industry Experts 👉 Gain Job-ready Skills 👉 24/7 Support 👉 Dedicated Learning Mentors 👉 Guaranteed Job Interviews 👉 Real-life Projects 👉 Get Certified 👉 Training at Feasible Time. For more information, please write back to us at info@mindmajix.com or call India : +91 905 240 3388 USA : +1 917 456 8403 Website: https://mindmajix.com #ManualTestingInterviewQuestions #ManualTestingInterviewQuestionsAndAnswers #ManualTestinginterview2025 #MindMajix #ManualTestinginterviewpreparation #ManualTestingIQ
- Cucumber Selenium Tutorial | Integrating Selenium with Cucumber BDD | Selenium Training | Edureka ** Selenium Certification Training: https://www.edureka.co/testing-with-selenium-webdriver ** This Edureka video on Cucumber Selenium Tutorial will help you understand how to integrate Cucumber with Selenium and execute the test cases. Below topics are covered in this video 1:11 - Introduction to Cucumber 2:13 - What is BDD? 3:53 - Introduction to Selenium 4:43 - Why use Cucumber with Selenium? 5:36 - Pre-requisites for using Cucumber 13:13 - Steps to create Cucumber Application Selenium playlist: https://goo.gl/NmuzXE Selenium Blog playlist: http://bit.ly/2B7C3QR - - - - - - - - - - - - - - - - - Subscribe to our channel to get video updates. Hit the subscribe button above: https://goo.gl/6ohpTV SlideShare: https://www.slideshare.net/edurekaIN Instagram: https://www.instagram.com/edureka_learning/ Facebook: https://www.facebook.com/edurekaIN/ Twitter: https://twitter.com/edurekain LinkedIn: https://www.linkedin.com/company/edureka - - - - - - - - - - - - - - - - - #edureka #edurekaselenium #cucumbersselenium #Selenium #SeleniumAutomation #SeleniumTesting #SeleniumTutorial #SeleniumTraining - - - - - - - - - - - - - - How it Works? 1. This is a 5 Week Instructor-led Online Course, 20 hours of assignment and 30 hours of project work 2. We have a 24x7 One-on-One LIVE Technical Support to help you with any problems you might face or any clarifications you may require during the course. 3. At the end of the training, you will have to undergo a 2-hour LIVE Practical Exam based on which we will provide you a Grade and a Verifiable Certificate! - - - - - - - - - - - - - - About the Course: Selenium is the most popular tool used to automate the testing of web applications. In this Course, you will learn about Selenium 3.0 and its various components such as Selenium IDE, Selenium WebDriver, and Selenium Grid. You learn to set up your environment so that you are ready to start using Selenium for testing your web applications. Browsers such as Chrome, Firefox, and IE are used to test web applications. In addition, you will experience to work with Selenium IDE, Selenium WebDriver, Selenium GRID, different frameworks such as Data Driven, Keyword Driven, Hybrid, and Cross-browser testing. Page Object Model (POM) is a design pattern that enables you to maintain reusability and readability of the automation scripts. This course introduces you to the concept of POM, and how to implement Page Classes and Page Factory to optimize the execution of automated scripts. In addition, you learn about various third-party tools such as Jenkins, TestNG, Sikuli, and AutoIT to optimally use them for performing various tasks in our browsers such as working with flash applications or Windows-based UI elements. Finally, you get introduced to Appium, an open source mobile application UI testing framework, and UIautomatorviewer. - - - - - - - - - - - - - - Who should go for this course? Selenium is a new and booming Technology in Software Industry that helps you automate the testing of your applications. Professionals with basic knowledge of Object Oriented Programming can easily take up this course. - - - - - - - - - - - - - - Why learn Selenium? For any project, Companies are rapidly inclining towards open source automated testing tools that will enable them to cut down the cost and effort that manual testing involves. Selenium is one such open source automated testing tool for websites. Performance, execution speed, and browser interaction of Selenium is too fast than any other automation tool. The test packages, the Modes of Selenium available for unattended execution, and the fact that the text script can be developed in any of the language that Selenium supports; makes Selenium the most desired automation testing tool. In addition, Selenium supports different operating systems along with support for different programming languages such as Python, Pearl, Ruby, PHP, .NET, C#, and Java; and various browsers, thereby making Selenium ahead of any other Automation tool. Customer Review: Tom Tully says, “I wanted to learn Selenium Webdriver in a live, real course, not self paced, so there would be pressure on me to finish. Edureka accomplished this at a price far lower than an in-person class, and as far as I know they are the only internet class that has live lectures on this subject. Teacher was very knowledgeable. I learned basic use of Selenium. No problem with me being in US and teacher in India. They have US 800 number.” - - - - - - - - - - - - - - For more information, Please write back to us at sales@edureka.in or call us at IND: 9606058406 / US: 18338555775 (toll free).

Topic 1: [('devops', np.float64(0.33773859945644186)), ('azure', np.float64(0.3286541133030725)), ('kubernetes', np.float64(0.3271147127025071)), ('cloud', np.float64(0.3116720413727872)), ('aws', np.float64(0.30846875173355265)), ('docker', np.float64(0.30193572354413845)), ('deployment', np.float64(0.3016558229936839)), ('azure devops', np.float64(0.28660721850161597)), ('continuous', np.float64(0.2832530106345693)), ('cicd', np.float64(0.2761588098211499))]
- What Is A Build Server In Continuous Integration? - Cloud Stack Studio What Is A Build Server In Continuous Integration? Have you ever wondered how software teams ensure their code is reliable and ready for deployment? In this video, we’ll explain the role of build servers in continuous integration and how they help streamline the software development process. We’ll start by defining what a build server is and how it automates tasks like compiling code, running tests, and verifying changes. You’ll learn how these servers monitor version control systems and trigger automated workflows whenever new code is committed. We’ll discuss how build servers provide rapid feedback to developers, catching issues early and maintaining a stable codebase. Additionally, we’ll explore how cloud platforms like Amazon Web Services, Microsoft Azure, and Google Cloud host these build services, offering scalable, secure environments that grow with your project needs. You’ll discover the main functions of build servers, including integration with deployment pipelines that facilitate continuous delivery. We’ll also cover best practices for maintaining security when using cloud-based build environments, such as isolating build processes and managing credentials carefully. Whether you’re new to DevOps or looking to improve your development workflow, understanding build servers is essential for delivering high-quality software efficiently. Join us for this insightful overview and subscribe for more updates on cloud infrastructure, automation tools, and best practices. ⬇️ Subscribe to our channel for more valuable insights. 🔗Subscribe: https://www.youtube.com/@CloudStackStudio/?sub_confirmation=1 #ContinuousIntegration #BuildServer #DevOpsTools #CloudInfrastructure #AWS #Azure #GoogleCloud #Automation #SoftwareTesting #CI About Us: Welcome to Cloud Stack Studio, your go-to channel for all things cloud infrastructure. We focus on key topics like AWS vs. Azure vs. Google Cloud, cloud security best practices, DevOps automation tools, and Kubernetes and containerization. Our mission is to provide informative content that helps you navigate cloud migration strategies, continuous integration and continuous deployment (CI/CD), and the culture of collaboration within DevOps.

In [12]:
from collections import defaultdict

# Topic IDs
topic_to_ids = defaultdict(list)

for doc_id, topic in zip(ids, topics):
    topic_to_ids[topic].append(doc_id)

# Topic Docs
topic_to_docs = defaultdict(list)

for doc_id, doc, topic in zip(ids, documents, topics):
    topic_to_docs[topic].append({
        "id": doc_id,
        "text": doc
    })

df = pd.DataFrame({
    "id": ids,
    "document": documents,
    "topic": topics
})

In [13]:
df_sorted = df.sort_values(by="topic")[["topic", "id", "document"]]

df_sorted.to_csv(f"{output_dir}/topic_documents.csv", index=False)

In [ ]:
model.save(f'{output_dir}/bt_48k_1203.model')
model.save(f'{output_dir}/bt_48k_1203.pickle', serialization="pickle")